### ISSUE TITLE
Feature Request: Support pre-auth command to refresh-token

### ISSUE THREAD

**Issue by Garethp** [mhassan1/yarn-plugin-aws-codeartifact#20]
I'd love the ability to define a pre-auth command to refresh the aws profile tokens in the config. Currently we have to refresh our tokens daily using `aws-azure-login`, it would be great if we could define  a JS script or shell command that would get executed before fetching credentials from Code Artifact

**Comment by mhassan1** [comment]
Thanks for the feature request. It seems like `aws-azure-login` presents you with an interactive prompt. Is that correct? If so, I imagine your expectation would be that the plugin should wait while you interact with that prompt. I'm not sure that would work inside a running `yarn` process, but we could try it.

**Comment by Garethp** [comment]
`aws-azure-login` actually provides a non-interactive mode with the `--no-prompt` option, but given that the feature request is just for the user pass in any given command in their config I could definitely see that some people might expect it to work with an interactive prompt
