### ISSUE TITLE
`decorateDefaultCredentialProvider` is deprecated

### ISSUE THREAD

**Issue by fatmcgav** [mhassan1/yarn-plugin-aws-codeartifact#49]
Hey there,

Firstly, thanks for this useful plugin.

Whilst I was trying to debug an issues one of our developers was having, I ended up in the `aws-sdk-js-v3` repo looking for the `decorateDefaultCredentialProvider` logic, and happened to spot that it's now deprecated.

See https://github.com/aws/aws-sdk-js-v3/pull/5681 for more info... It looks like this deprecation was first introduced in `3.502.0` of the SDK.

**Comment by mhassan1** [comment]
Thanks for the report!
